name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build workspace (incl. desktop)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Build all crates
        run: cargo build --workspace
