name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          npm install

      - name: Run unit and integration tests
        run: cargo test --workspace
